apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service-caller.fullname" . }}
  labels:
    {{- include "service-caller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "service-caller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "service-caller.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["-c", "while true; do curl -s http://nginx-web:80; echo \"Time: $(date)\"; sleep 5; done"]
