{{- if .Values.secrets.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx.fullname" . }}-auth
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
type: Opaque
data:
  BASIC_AUTH_USERNAME: {{ .Values.secrets.basicAuth.username | b64enc }}
  BASIC_AUTH_PASSWORD: {{ .Values.secrets.basicAuth.password | b64enc }}
{{- end }}