# Default values for the NGINX Helm chart

replicaCount: 1

image:
  repository: nginx
  tag: "1.21.6"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

# New Ingress configuration
ingress:
  enabled: true
  className: "nginx-custom"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: nginx.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
  # - secretName: nginx-tls
  #   hosts:
  #     - nginx.example.com

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Content for the HTML page
htmlContent: |
  <!DOCTYPE html>
  <html>
  <head>
    <title>Welcome to NGINX on Kubernetes!</title>
    <style>
      body {
        font-family: Arial, sans-serif;
        line-height: 1.6;
        color: #333;
        max-width: 800px;
        margin: 0 auto;
        padding: 2em;
      }
      h1 {
        color: #0066cc;
      }
      .container {
        border: 1px solid #ddd;
        padding: 2em;
        border-radius: 5px;
        background-color: #f9f9f9;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>NGINX Deployed with Kubernetes and Helm!</h1>
      <p>If you're seeing this page, it means your NGINX server has been successfully deployed to Kubernetes using a Helm chart.</p>
      <p>This content is being served from a Kubernetes ConfigMap.</p>
      <p>You are accessing this page through an Ingress!</p>
    </div>
  </body>
  </html>

# Environment variables for NGINX
env:
  - name: NGINX_HOST
    value: "kubernetes.example.com"
  - name: NGINX_PORT
    value: "80"

# Secret values (in production, don't store actual secrets in values.yaml)
secrets:
  basicAuth:
    enabled: false
    username: admin
    password: changeme

# Volume configurations
volumes:
  # For persistent storage if needed
  persistentVolume:
    enabled: false
    size: 1Gi
    storageClass: ""