apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-caller.fullname" . }}
  labels:
    {{- include "nginx-caller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-caller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-caller.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["/scripts/caller.sh"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: script-volume
              mountPath: /scripts
      volumes:
        - name: script-volume
          configMap:
            name: {{ include "nginx-caller.fullname" . }}-script
            defaultMode: 0755