apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-web.fullname" . }}
  labels:
    app: {{ include "nginx-web.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "nginx-web.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "nginx-web.fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        env:
        - name: NGINX_PORT
          value: "{{ .Values.environment.NGINX_PORT }}"
        - name: NGINX_HOST
          value: {{ .Values.environment.NGINX_HOST }}
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
        - name: nginx-content
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: nginx-config
        configMap:
          name: {{ include "nginx-web.fullname" . }}-config
      - name: nginx-content
        configMap:
          name: {{ include "nginx-web.fullname" . }}-config
