apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx-web.fullname" . }}-secret
type: Opaque
data:
  basic-auth-user: {{ .Values.secrets.BASIC_AUTH_USER | b64enc }}
  basic-auth-pass: {{ .Values.secrets.BASIC_AUTH_PASS | b64enc }}
